script: |
  cd /mnt/HDD1/docker/vendors_fastapi
  
  # Dockerfile이 있는지 확인하고 없으면 생성
  if [ ! -f "Dockerfile" ]; then
    cat > Dockerfile << 'EOF'
  FROM python:3.12-slim
  RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
  WORKDIR /app
  RUN git clone https://github.com/dbspgnl/gitaction.git /app/source
  COPY requirements.txt .
  RUN pip install --no-cache-dir -r requirements.txt
  EXPOSE 8000
  CMD ["sh", "-c", "cd /app/source && git pull origin master && cp -r * /app/ && cd /app && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
  EOF
  fi
  
  docker stop fastapi-app || true
  docker rm fastapi-app || true
  docker build -t fastapi-app .
  docker run -d --name fastapi-app -p 8000:8000 --restart unless-stopped fastapi-app